version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli
      - set -x   # enable debug for install phase

  pre_build:
    commands:
      - echo "Setting version from Git commit..."
      - export VERSION=$(git rev-parse --short HEAD)
      - echo "Version set to $VERSION"
      - set -x   # enable debug for pre_build phase

  build:
    commands:
      - echo "Building project..."
      - mkdir -p dist
      - echo "Hello from Build ${VERSION}" > dist/index.html
      - zip -r build_${VERSION}.zip dist appspec.yml scripts/
      - echo "Files in current directory:"
      - ls -l
      - set -x   # enable debug for build phase

  post_build:
    commands:
      - set -x   # enable debug for post_build
      - echo "Uploading artifact to S3..."
      - aws s3 cp build_${VERSION}.zip s3://baskaran-cloud-builds/releases/build_${VERSION}.zip
      - echo "Triggering deployment in CodeDeploy..."
      - aws deploy create-deployment \
          --application-name cloud-deploy-app \
          --deployment-group-name cloud-deploy-group \
          --s3-location bucket=baskaran-cloud-builds,bundleType=zip,key=releases/build_${VERSION}.zip
      - echo "Build and deployment triggered successfully!"

artifacts:
  files:
    - build_*.zip
