version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Setting version from Git commit"
      - VERSION=$(git rev-parse --short HEAD)
      - echo "Version set to $VERSION"

  build:
    commands:
      - echo "Building project..."
      - mkdir -p dist
      - echo "Hello from Build ${VERSION}" > dist/index.html
      - zip -r build_${VERSION}.zip dist appspec.yml scripts/

  post_build:
    commands:
      - echo "Uploading artifact to S3"
      - aws s3 cp build_${VERSION}.zip s3://baskaran-cloud-builds/releases/
      - echo "Creating deployment in CodeDeploy"
      - |
        aws deploy create-deployment \
          --application-name cloud-deploy-app \
          --deployment-group-name cloud-deploy-group \
          --s3-location bucket=baskaran-cloud-builds,bundleType=zip,key=releases/build_${VERSION}.zip

artifacts:
  files:
    - build_*.zip
